title: Todd's Technical Treasures
description: >- # this means to ignore newlines until "baseurl:"
  Howtos, system setup notes, examples
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tstellanova.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: stellanovat
github_username:  tstellanova

# Build settings
theme: minima

show_excerpts: true

plugins:
  - jekyll-sitemap
  - jekyll-feed

feed:
  path: atom.xml

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
