title: Todd's Technical Treasures
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  FUBARN
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: stellanovat
github_username:  tstellanova

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
